### ISSUE TITLE
Conflicts!

### ISSUE THREAD

**Issue by AlvaroCavalcante** [harsh2912/Background--removal#1]
Hello, I was reading your tutorial and trying to replicate in my machine (and also in Google Collab later). I cloned this repo and ran the command to create the matting environment with the requirements.yml that is inside de API/ folder. The problem is that when I try to create the env, the following error raises:
![image](https://user-images.githubusercontent.com/37350513/93550309-8226e900-f941-11ea-8078-bc5a3d021bdc.png)

It takes some minutes but has no success to install and create the env. The other conda env "segmentation" was successfully created. Some ideas about what is happening?

**Comment by harsh2912** [comment]
Hi , I may not know the exact reason for this. But that can be because of the conda version that you are using. They have a discussion about this kind of problem [here](https://stackoverflow.com/questions/57518050/conda-install-and-update-do-not-work-also-solving-environment-get-errors). Please let me know if any of these solved your issue or not. If not I would love to help you solve the issue.

**Comment by AlvaroCavalcante** [comment]
Tanks for your comment, I'll try to solve this issue, could you tell me which conda version are you using? Tanks for your awesome work!

**Comment by harsh2912** [comment]
Hi, I am using conda version 4.8.3

**Comment by its-jd** [comment]
Hi, I am also stuck with the same issue,
could you please tell me if you have found the solution?

**Comment by harsh2912** [comment]
He solved by updating the conda
